// <auto-generated />
using System;
using EbookManager.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EbookManager.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20260827150943_AddMetadataQualityExclusions")]
    partial class AddMetadataQualityExclusions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("EbookManager.Infrastructure.Persistence.Entities.AuthorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Authors", (string)null);
                });

            modelBuilder.Entity("EbookManager.Infrastructure.Persistence.Entities.BookAuthorEntity", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("BookId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("BookId", "Order")
                        .IsUnique();

                    b.ToTable("BookAuthors", (string)null);
                });

            modelBuilder.Entity("EbookManager.Infrastructure.Persistence.Entities.BookEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("CoverBytes")
                        .HasColumnType("BLOB");

                    b.Property<string>("CoverRelativePath")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DuplicateKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Isbn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReadingStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Series")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SeriesNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DuplicateKey")
                        .IsUnique();

                    b.HasIndex("NormalizedTitle");

                    b.HasIndex("NormalizedTitle", "Id")
                        .HasDatabaseName("IX_Books_NormalizedTitle_Id");

                    b.ToTable("Books", (string)null);
                });

            modelBuilder.Entity("EbookManager.Infrastructure.Persistence.Entities.BookFileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BookId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WriteBackMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("WriteBackStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("Sha256")
                        .IsUnique();

                    b.ToTable("BookFiles", (string)null);
                });

            modelBuilder.Entity("EbookManager.Infrastructure.Persistence.Entities.BookTagEntity", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("BookId", "TagId");

                    b.HasIndex("TagId");

                    b.HasIndex("BookId", "Order")
                        .IsUnique();

                    b.ToTable("BookTags", (string)null);
                });

            modelBuilder.Entity("EbookManager.Infrastructure.Persistence.Entities.CustomMetadataFieldEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.HasIndex("SortOrder", "Name", "Id");

                    b.ToTable("CustomMetadataFields", (string)null);
                });

            modelBuilder.Entity("EbookManager.Infrastructure.Persistence.Entities.CustomMetadataValueEntity", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("BooleanValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DateValue")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NumberValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("TextValue")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("BookId", "FieldId");

                    b.HasIndex("FieldId");

                    b.ToTable("CustomMetadataValues", (string)null);
                });

            modelBuilder.Entity("EbookManager.Infrastructure.Persistence.Entities.DuplicateExclusionEntity", b =>
                {
                    b.Property<Guid>("FirstBookId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SecondBookId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("FirstBookId", "SecondBookId");

                    b.HasIndex("SecondBookId");

                    b.ToTable("DuplicateExclusions", (string)null);
                });

            modelBuilder.Entity("EbookManager.Infrastructure.Persistence.Entities.ImportItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("AvailabilityCheckMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("BookId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CleanupMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DatabaseSaveMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DuplicateCheckMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Format")
                        .HasColumnType("TEXT");

                    b.Property<long?>("HashingMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ImportRunId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ManagedCopyMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("MetadataReadMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SizeReadMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SuggestedAuthors")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SuggestedBookId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SuggestedTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("SuggestionKind")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("ImportRunId", "Sequence")
                        .IsUnique();

                    b.ToTable("ImportItems", (string)null);
                });

            modelBuilder.Entity("EbookManager.Infrastructure.Persistence.Entities.ImportRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IncludeSubdirectories")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePath")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ImportRuns", (string)null);
                });

            modelBuilder.Entity("EbookManager.Infrastructure.Persistence.Entities.MetadataQualityExclusionEntity", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SignalKey")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("BookId", "SignalKey");

                    b.ToTable("MetadataQualityExclusions", (string)null);
                });

            modelBuilder.Entity("EbookManager.Infrastructure.Persistence.Entities.TagEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("EbookManager.Infrastructure.Persistence.Entities.BookAuthorEntity", b =>
                {
                    b.HasOne("EbookManager.Infrastructure.Persistence.Entities.AuthorEntity", "Author")
                        .WithMany("BookAuthors")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EbookManager.Infrastructure.Persistence.Entities.BookEntity", "Book")
                        .WithMany("BookAuthors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("EbookManager.Infrastructure.Persistence.Entities.BookFileEntity", b =>
                {
                    b.HasOne("EbookManager.Infrastructure.Persistence.Entities.BookEntity", "Book")
                        .WithMany("Files")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("EbookManager.Infrastructure.Persistence.Entities.BookTagEntity", b =>
                {
                    b.HasOne("EbookManager.Infrastructure.Persistence.Entities.BookEntity", "Book")
                        .WithMany("BookTags")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EbookManager.Infrastructure.Persistence.Entities.TagEntity", "Tag")
                        .WithMany("BookTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("EbookManager.Infrastructure.Persistence.Entities.CustomMetadataValueEntity", b =>
                {
                    b.HasOne("EbookManager.Infrastructure.Persistence.Entities.BookEntity", "Book")
                        .WithMany("CustomMetadataValues")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EbookManager.Infrastructure.Persistence.Entities.CustomMetadataFieldEntity", "Field")
                        .WithMany("Values")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Field");
                });

            modelBuilder.Entity("EbookManager.Infrastructure.Persistence.Entities.DuplicateExclusionEntity", b =>
                {
                    b.HasOne("EbookManager.Infrastructure.Persistence.Entities.BookEntity", "FirstBook")
                        .WithMany()
                        .HasForeignKey("FirstBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EbookManager.Infrastructure.Persistence.Entities.BookEntity", "SecondBook")
                        .WithMany()
                        .HasForeignKey("SecondBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FirstBook");

                    b.Navigation("SecondBook");
                });

            modelBuilder.Entity("EbookManager.Infrastructure.Persistence.Entities.ImportItemEntity", b =>
                {
                    b.HasOne("EbookManager.Infrastructure.Persistence.Entities.BookEntity", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EbookManager.Infrastructure.Persistence.Entities.ImportRunEntity", "ImportRun")
                        .WithMany("Items")
                        .HasForeignKey("ImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("ImportRun");
                });

            modelBuilder.Entity("EbookManager.Infrastructure.Persistence.Entities.MetadataQualityExclusionEntity", b =>
                {
                    b.HasOne("EbookManager.Infrastructure.Persistence.Entities.BookEntity", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("EbookManager.Infrastructure.Persistence.Entities.AuthorEntity", b =>
                {
                    b.Navigation("BookAuthors");
                });

            modelBuilder.Entity("EbookManager.Infrastructure.Persistence.Entities.BookEntity", b =>
                {
                    b.Navigation("BookAuthors");

                    b.Navigation("BookTags");

                    b.Navigation("CustomMetadataValues");

                    b.Navigation("Files");
                });

            modelBuilder.Entity("EbookManager.Infrastructure.Persistence.Entities.CustomMetadataFieldEntity", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("EbookManager.Infrastructure.Persistence.Entities.ImportRunEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("EbookManager.Infrastructure.Persistence.Entities.TagEntity", b =>
                {
                    b.Navigation("BookTags");
                });
#pragma warning restore 612, 618
        }
    }
}
